# Generated by Django 4.1.3 on 2022-11-01 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mileage', models.FloatField()),
                ('price', models.FloatField()),
                ('dealer_name', models.CharField(max_length=255)),
                ('carURL', models.CharField(max_length=255)),
            ],
        ),
    ]
