# Generated by Django 4.1.3 on 2022-11-30 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField(max_length=8)),
                ('mileage', models.CharField(max_length=8)),
                ('dealer_name', models.CharField(max_length=255)),
                ('carURL', models.CharField(max_length=500)),
            ],
        ),
    ]
