# Generated by Django 4.1.3 on 2022-11-16 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
    #     migrations.RunSQL("""
    #         INSERT INTO cars (title)
    #         VALUES ('collection1')
    #     """, """
    #         DELETE FROM cars
    #         WHERE title='collection1'
    #     """)
    ]
