# Generated by Django 4.1.3 on 2022-11-16 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='number',
        ),
    ]
